/*
# Seed permissions (with display_name)
*/

INSERT INTO permissions (name, display_name, module, action, description) VALUES
    ('dashboard.view', 'View Dashboard', 'dashboard', 'view', 'View dashboard'),
    ('users.view', 'View Users', 'users', 'view', 'View user list'),
    ('users.create', 'Create Users', 'users', 'create', 'Create new users'),
    ('users.edit', 'Edit Users', 'users', 'edit', 'Edit user details'),
    ('users.delete', 'Delete Users', 'users', 'delete', 'Delete users'),
    ('users.activate', 'Activate Users', 'users', 'activate', 'Activate/deactivate users'),
    ('users.reset_password', 'Reset Password', 'users', 'reset_password', 'Reset user passwords'),
    ('users.assign_role', 'Assign Role', 'users', 'assign_role', 'Assign roles to users'),
    ('users.assign_branch', 'Assign Branch', 'users', 'assign_branch', 'Assign branch to users'),
    ('users.assign_class', 'Assign Class', 'users', 'assign_class', 'Assign class/section to users'),
    ('roles.view', 'View Roles', 'roles', 'view', 'View roles'),
    ('roles.manage', 'Manage Roles', 'roles', 'manage', 'Create and edit roles'),
    ('permissions.view', 'View Permissions', 'permissions', 'view', 'View permissions'),
    ('permissions.manage', 'Manage Permissions', 'permissions', 'manage', 'Assign permissions to roles'),
    ('students.view', 'View Students', 'students', 'view', 'View student records'),
    ('students.create', 'Create Students', 'students', 'create', 'Create student records'),
    ('students.edit', 'Edit Students', 'students', 'edit', 'Edit student records'),
    ('students.delete', 'Delete Students', 'students', 'delete', 'Delete student records'),
    ('teachers.view', 'View Teachers', 'teachers', 'view', 'View teacher records'),
    ('teachers.create', 'Create Teachers', 'teachers', 'create', 'Create teacher records'),
    ('teachers.edit', 'Edit Teachers', 'teachers', 'edit', 'Edit teacher records'),
    ('teachers.delete', 'Delete Teachers', 'teachers', 'delete', 'Delete teacher records'),
    ('parents.view', 'View Parents', 'parents', 'view', 'View parent records'),
    ('parents.create', 'Create Parents', 'parents', 'create', 'Create parent records'),
    ('parents.edit', 'Edit Parents', 'parents', 'edit', 'Edit parent records'),
    ('parents.delete', 'Delete Parents', 'parents', 'delete', 'Delete parent records'),
    ('classes.view', 'View Classes', 'classes', 'view', 'View classes'),
    ('classes.create', 'Create Classes', 'classes', 'create', 'Create classes'),
    ('classes.edit', 'Edit Classes', 'classes', 'edit', 'Edit classes'),
    ('classes.delete', 'Delete Classes', 'classes', 'delete', 'Delete classes'),
    ('attendance.view', 'View Attendance', 'attendance', 'view', 'View attendance records'),
    ('attendance.mark', 'Mark Attendance', 'attendance', 'mark', 'Mark attendance'),
    ('attendance.edit', 'Edit Attendance', 'attendance', 'edit', 'Edit attendance records'),
    ('exams.view', 'View Exams', 'exams', 'view', 'View examinations'),
    ('exams.create', 'Create Exams', 'exams', 'create', 'Create examinations'),
    ('exams.edit', 'Edit Exams', 'exams', 'edit', 'Edit examinations'),
    ('exams.delete', 'Delete Exams', 'exams', 'delete', 'Delete examinations'),
    ('marks.view', 'View Marks', 'marks', 'view', 'View marks/grades'),
    ('marks.enter', 'Enter Marks', 'marks', 'enter', 'Enter marks/grades'),
    ('marks.edit', 'Edit Marks', 'marks', 'edit', 'Edit marks/grades'),
    ('homework.view', 'View Homework', 'homework', 'view', 'View homework'),
    ('homework.create', 'Create Homework', 'homework', 'create', 'Create homework'),
    ('homework.edit', 'Edit Homework', 'homework', 'edit', 'Edit homework'),
    ('homework.delete', 'Delete Homework', 'homework', 'delete', 'Delete homework'),
    ('assignments.view', 'View Assignments', 'assignments', 'view', 'View assignments'),
    ('assignments.create', 'Create Assignments', 'assignments', 'create', 'Create assignments'),
    ('assignments.edit', 'Edit Assignments', 'assignments', 'edit', 'Edit assignments'),
    ('fees.view', 'View Fees', 'fees', 'view', 'View fee records'),
    ('fees.create', 'Create Fees', 'fees', 'create', 'Create fee records'),
    ('fees.edit', 'Edit Fees', 'fees', 'edit', 'Edit fee records'),
    ('fees.collect', 'Collect Fees', 'fees', 'collect', 'Collect fee payments'),
    ('fees.reports', 'Fee Reports', 'fees', 'reports', 'View fee reports'),
    ('library.view', 'View Library', 'library', 'view', 'View library books'),
    ('library.manage', 'Manage Library', 'library', 'manage', 'Manage library inventory and issues'),
    ('transport.view', 'View Transport', 'transport', 'view', 'View transport routes'),
    ('transport.manage', 'Manage Transport', 'transport', 'manage', 'Manage transport routes and assignments'),
    ('events.view', 'View Events', 'events', 'view', 'View events'),
    ('events.manage', 'Manage Events', 'events', 'manage', 'Create and edit events'),
    ('gallery.view', 'View Gallery', 'gallery', 'view', 'View gallery'),
    ('gallery.manage', 'Manage Gallery', 'gallery', 'manage', 'Manage gallery albums and photos'),
    ('announcements.view', 'View Announcements', 'announcements', 'view', 'View announcements'),
    ('announcements.manage', 'Manage Announcements', 'announcements', 'manage', 'Create and edit announcements'),
    ('reports.view', 'View Reports', 'reports', 'view', 'View reports'),
    ('reports.generate', 'Generate Reports', 'reports', 'generate', 'Generate and export reports'),
    ('settings.view', 'View Settings', 'settings', 'view', 'View settings'),
    ('settings.manage', 'Manage Settings', 'settings', 'manage', 'Manage system settings'),
    ('settings.super_admin', 'Super Admin Settings', 'settings', 'super_admin', 'Super admin only settings'),
    ('messages.view', 'View Messages', 'messages', 'view', 'View messages'),
    ('messages.send', 'Send Messages', 'messages', 'send', 'Send messages'),
    ('admissions.view', 'View Admissions', 'admissions', 'view', 'View admissions'),
    ('admissions.manage', 'Manage Admissions', 'admissions', 'manage', 'Manage admissions'),
    ('visitors.view', 'View Visitors', 'visitors', 'view', 'View visitor logs'),
    ('visitors.manage', 'Manage Visitors', 'visitors', 'manage', 'Manage visitor logs')
ON CONFLICT (name) DO NOTHING;
